# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96e0f38664e931cda028813cf260fd4ecff16c3d97caa015ffe42cbda35954f124fc5fdab6c3b1e554c005797ca8c373ef568eb91ad16d2a1f390b8c43408451

test:
  secret_key_base: 70e56f7d85d3dd5c010076c86d8fda24c57007c819f2cb8097f039a65c74f175b67fc71f2dbc5a732d3cf164bb40b916c4be6b109b11143927278406ec0127e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
